name = "store-management-jobs"
main = "src/index.ts"
compatibility_date = "2026-07-27"
compatibility_flags = ["nodejs_compat"]

[[queues.consumers]]
queue = "store-management-domain-events"
max_batch_size = 10
max_batch_timeout = 5
