import type { MoneyV1, QuantityV1 } from "../../packages/contracts/src/v1/index.js";
import type { RequestContext } from "../../packages/foundation/src/context.js";
import type { TransactionClient } from "../../packages/foundation/src/db.js";
import { PlatformError } from "../../packages/foundation/src/errors.js";
import { InventoryOperationsSqlRepository } from "../inventory/operations-sql-repository.js";
import type { StockPostingLine, StockStatus } from "../inventory/types.js";
import { ProcurementSqlRepository } from "./sql-repository.js";

const DECIMAL = /^-?\d+(?:\.\d+)?$/u;
const INTEGER = /^-?\d+$/u;
function factor(scale: number): bigint { if (!Number.isInteger(scale) || scale < 0 || scale > 18) throw new PlatformError("VALIDATION_FAILED", "Invalid scale", 400); return 10n ** BigInt(scale); }
function parseQuantity(value: QuantityV1): bigint { const raw = value.amount.trim(); if (!DECIMAL.test(raw)) throw new PlatformError("VALIDATION_FAILED", "Quantity must be an exact decimal string", 400); const negative = raw.startsWith("-"); const unsigned = negative ? raw.slice(1) : raw; const [whole = "0", fraction = ""] = unsigned.split("."); if (fraction.length > value.scale) throw new PlatformError("VALIDATION_FAILED", "Quantity precision exceeds scale", 400); const amount = BigInt(`${whole}${fraction.padEnd(value.scale, "0")}`.replace(/^0+(?=\d)/u, "") || "0"); return negative ? -amount : amount; }
function parseMoney(value: MoneyV1): bigint { if (!INTEGER.test(value.amountMinor)) throw new PlatformError("VALIDATION_FAILED", "Money must be an integer minor-unit string", 400); return BigInt(value.amountMinor); }
function required(value: string, field: string): string { const normalized = value.trim(); if (!normalized) throw new PlatformError("VALIDATION_FAILED", `${field} is required`, 400); return normalized; }

export class ProcurementOperationsSqlRepository extends ProcurementSqlRepository {
  private readonly inventoryOperations: InventoryOperationsSqlRepository;
  constructor(inventory = new InventoryOperationsSqlRepository()) { super(inventory); this.inventoryOperations = inventory; }

  async createRequisition(client: TransactionClient, context: RequestContext, input: { readonly id: string; readonly legalEntityId: string; readonly lines: readonly { readonly id: string; readonly itemId: string; readonly variantId: string; readonly warehouseId: string; readonly quantity: QuantityV1; readonly requiredBy: string; readonly preferredSupplierId?: string; readonly estimatedUnitCost?: MoneyV1; readonly reason: string }[] }): Promise<Record<string, unknown>> {
    if (input.lines.length === 0) throw new PlatformError("VALIDATION_FAILED", "Requisition requires lines", 400); const replay = await client.query(`SELECT id::text,state,version::text FROM procurement.purchase_requisitions WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, input.id]); if (replay.rows[0]) return replay.rows[0];
    await client.query(`INSERT INTO procurement.purchase_requisitions(id,tenant_id,legal_entity_id,requested_by) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid)`, [input.id, context.tenantId, input.legalEntityId, context.actorId]);
    for (const line of input.lines) { const quantity = parseQuantity(line.quantity); if (quantity <= 0n) throw new PlatformError("VALIDATION_FAILED", "Requisition quantity must be positive", 400); const estimated = line.estimatedUnitCost ? parseMoney(line.estimatedUnitCost) : undefined; await client.query(`INSERT INTO procurement.purchase_requisition_lines(id,tenant_id,requisition_id,item_id,variant_id,warehouse_id,quantity,quantity_scale,unit_code,required_by,preferred_supplier_id,estimated_unit_cost_minor,currency,reason) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6::uuid,$7::numeric,$8,$9,$10::date,$11::uuid,$12::numeric,$13,$14)`, [line.id, context.tenantId, input.id, line.itemId, line.variantId, line.warehouseId, quantity.toString(), line.quantity.scale, line.quantity.unit, line.requiredBy, line.preferredSupplierId ?? null, estimated?.toString() ?? null, line.estimatedUnitCost?.currency ?? null, required(line.reason, "Requisition reason")]); }
    await this.auditAndPublish(client, context, "procurement.requisition.created.v1", "purchase_requisition", input.id, { lineCount: input.lines.length }); return { id: input.id, state: "draft", version: "1" };
  }

  async submitRequisition(client: TransactionClient, context: RequestContext, requisitionId: string, expectedVersion: number): Promise<Record<string, unknown>> {
    const result = await client.query(`UPDATE procurement.purchase_requisitions SET state='submitted',updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid AND state='draft' AND version=$3 RETURNING id::text,state,version::text`, [context.tenantId, requisitionId, expectedVersion]); if (result.rowCount !== 1) throw new PlatformError("VERSION_CONFLICT", "Requisition state or version changed", 409); await this.auditAndPublish(client, context, "procurement.requisition.submitted.v1", "purchase_requisition", requisitionId, {}); return result.rows[0]!;
  }

  async approveRequisition(client: TransactionClient, context: RequestContext, input: { readonly requisitionId: string; readonly approvalId: string; readonly expectedVersion: number }): Promise<Record<string, unknown>> {
    const approval = await client.query(`SELECT id FROM platform.approval_requests WHERE tenant_id=$1::uuid AND id=$2::uuid AND status='approved' AND target_type='purchase_requisition' AND target_id=$3`, [context.tenantId, input.approvalId, input.requisitionId]); if (approval.rowCount !== 1) throw new PlatformError("PERMISSION_DENIED", "Approved requisition approval is required", 403); const result = await client.query(`UPDATE procurement.purchase_requisitions SET state='approved',approved_by=$3::uuid,approval_id=$4::uuid,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid AND state='submitted' AND version=$5 RETURNING id::text,state,version::text`, [context.tenantId, input.requisitionId, context.actorId, input.approvalId, input.expectedVersion]); if (result.rowCount !== 1) throw new PlatformError("VERSION_CONFLICT", "Requisition state or version changed", 409); await this.auditAndPublish(client, context, "procurement.requisition.approved.v1", "purchase_requisition", input.requisitionId, { approvalId: input.approvalId }); return result.rows[0]!;
  }

  async postSupplierReturn(client: TransactionClient, context: RequestContext, input: { readonly id: string; readonly goodsReceiptId: string; readonly operationId: string; readonly postingGroupId: string; readonly lines: readonly { readonly id: string; readonly goodsReceiptLineId: string; readonly quantity: QuantityV1; readonly reason: string }[] }): Promise<Record<string, unknown>> {
    if (input.lines.length === 0) throw new PlatformError("VALIDATION_FAILED", "Supplier return requires lines", 400); const replay = await client.query(`SELECT id::text,state,posting_group_id FROM procurement.supplier_returns WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, input.id]); if (replay.rows[0]) return replay.rows[0];
    const receipt = await client.query<{ legal_entity_id: string; supplier_id: string; state: string } & Record<string, unknown>>(`SELECT legal_entity_id::text,supplier_id::text,state FROM procurement.goods_receipts WHERE tenant_id=$1::uuid AND id=$2::uuid FOR UPDATE`, [context.tenantId, input.goodsReceiptId]); const header = receipt.rows[0]; if (!header) throw new PlatformError("NOT_FOUND", "Goods receipt not found", 404); if (header.state !== "posted") throw new PlatformError("CONFLICT", "Only posted receipts can be returned", 409);
    const receiptLines = await client.query<{ id: string; item_id: string; variant_id: string; warehouse_id: string; received_quantity: string; quantity_scale: number; unit_code: string; disposition: string; unit_cost_minor: string; currency: string; batch_id: string | null; serial_ids: string[]; expiry_date: string | null } & Record<string, unknown>>(`SELECT id::text,item_id::text,variant_id::text,warehouse_id::text,received_quantity::text,quantity_scale,unit_code,disposition,unit_cost_minor::text,currency,batch_id::text,serial_ids::text[],expiry_date::text FROM procurement.goods_receipt_lines WHERE tenant_id=$1::uuid AND goods_receipt_id=$2::uuid ORDER BY id FOR UPDATE`, [context.tenantId, input.goodsReceiptId]); const byId = new Map(receiptLines.rows.map((line) => [line.id, line])); const postings: StockPostingLine[] = []; const prepared: { input: typeof input.lines[number]; line: typeof receiptLines.rows[number]; amount: bigint }[] = [];
    for (const requested of input.lines) { const line = byId.get(requested.goodsReceiptLineId); if (!line) throw new PlatformError("VALIDATION_FAILED", "Unknown receipt line", 400); if (line.disposition === "rejected") throw new PlatformError("CONFLICT", "Rejected quantity never entered stock", 409); if (requested.quantity.unit !== line.unit_code || requested.quantity.scale !== line.quantity_scale) throw new PlatformError("VALIDATION_FAILED", "Return dimensions mismatch", 400); const amount = parseQuantity(requested.quantity); if (amount <= 0n) throw new PlatformError("VALIDATION_FAILED", "Return quantity must be positive", 400); const prior = await client.query<{ amount: string } & Record<string, unknown>>(`SELECT COALESCE(SUM(quantity),0)::text AS amount FROM procurement.supplier_return_lines WHERE tenant_id=$1::uuid AND goods_receipt_line_id=$2::uuid`, [context.tenantId, line.id]); if (BigInt(prior.rows[0]?.amount ?? "0") + amount > BigInt(line.received_quantity)) throw new PlatformError("CONFLICT", "Supplier return exceeds received quantity", 409); const status: StockStatus = line.disposition === "accepted" ? "sellable" : line.disposition === "quarantine" ? "quarantine" : "damaged"; const common = { item: { itemId: line.item_id, variantId: line.variant_id }, warehouseId: line.warehouse_id, stockStatus: status, unitCostMinor: line.unit_cost_minor, currency: line.currency, sourceDocumentId: input.id, sourceDocumentLineId: requested.id, ...(line.batch_id ? { batchId: line.batch_id } : {}), ...(line.expiry_date ? { expiryDate: line.expiry_date } : {}) }; if (line.serial_ids.length > 0) { const units = Number(amount / factor(line.quantity_scale)); const returned = Number(BigInt(prior.rows[0]?.amount ?? "0") / factor(line.quantity_scale)); for (const serialId of line.serial_ids.slice(returned, returned + units)) postings.push({ ...common, serialId, quantityDelta: { amount: "-1", unit: line.unit_code, scale: line.quantity_scale } }); } else postings.push({ ...common, quantityDelta: { amount: `-${requested.quantity.amount}`, unit: line.unit_code, scale: line.quantity_scale } }); prepared.push({ input: requested, line, amount }); }
    await client.query(`INSERT INTO procurement.supplier_returns(id,tenant_id,legal_entity_id,supplier_id,goods_receipt_id,returned_by,business_date,posting_group_id) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6::uuid,$7::date,$8)`, [input.id, context.tenantId, header.legal_entity_id, header.supplier_id, input.goodsReceiptId, context.actorId, context.businessDate, input.postingGroupId]); const posting = await this.inventoryOperations.postStock(client, context, { schemaVersion: "1.0", context: { tenantId: context.tenantId, legalEntityId: header.legal_entity_id, actorId: context.actorId, locale: context.locale, timeZone: context.timeZone, businessDate: context.businessDate }, operationId: input.operationId, postingGroupId: input.postingGroupId, movementType: "supplier_return", sourceDocumentType: "supplier_return", lines: postings, audit: { actorId: context.actorId, requestId: context.requestId, traceId: context.traceId } }); const ledgerByLine = new Map<string, string[]>(); for (const entry of posting.entries) { if (!entry.sourceDocumentLineId) continue; const ids = ledgerByLine.get(entry.sourceDocumentLineId) ?? []; ids.push(entry.id); ledgerByLine.set(entry.sourceDocumentLineId, ids); }
    for (const item of prepared) await client.query(`INSERT INTO procurement.supplier_return_lines(id,tenant_id,supplier_return_id,goods_receipt_line_id,item_id,variant_id,warehouse_id,quantity,quantity_scale,unit_code,unit_cost_minor,currency,reason,stock_ledger_entry_ids) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6::uuid,$7::uuid,$8::numeric,$9,$10,$11::numeric,$12,$13,$14::uuid[])`, [item.input.id, context.tenantId, input.id, item.line.id, item.line.item_id, item.line.variant_id, item.line.warehouse_id, item.amount.toString(), item.line.quantity_scale, item.line.unit_code, item.line.unit_cost_minor, item.line.currency, required(item.input.reason, "Return reason"), ledgerByLine.get(item.input.id) ?? []]);
    await this.auditAndPublish(client, context, "procurement.supplier_return.posted.v1", "supplier_return", input.id, { goodsReceiptId: input.goodsReceiptId, postingGroupId: input.postingGroupId }); return { id: input.id, state: "posted", postingGroupId: input.postingGroupId, returnedAt: posting.postedAt };
  }
}
