analyzer:
  exclude:
    - "**/.dart_tool/**"
    - "**/build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_use_of_visible_for_testing_member: error
    missing_required_param: error
    missing_return: error
    todo: warning

linter:
  rules:
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    collection_methods_unrelated_type: true
    combinators_ordering: true
    curly_braces_in_flow_control_structures: true
    dangling_library_doc_comments: true
    depend_on_referenced_packages: true
    directives_ordering: true
    discarded_futures: true
    empty_catches: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    implicit_call_tearoffs: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    library_annotations: true
    no_adjacent_strings_in_list: true
    no_default_cases: true
    no_duplicate_case_values: true
    no_leading_underscores_for_library_prefixes: true
    no_literal_bool_comparisons: true
    noop_primitive_operations: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: false
    require_trailing_commas: true
    secure_pubspec_urls: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    use_enums: true
    use_named_constants: true
    use_raw_strings: true
    use_string_buffers: true
