import type { QuantityV1 } from "../../packages/contracts/src/v1/index.js";
import type { RequestContext } from "../../packages/foundation/src/context.js";
import type { TransactionClient } from "../../packages/foundation/src/db.js";
import { PlatformError } from "../../packages/foundation/src/errors.js";
import { uuidV7 } from "../../packages/foundation/src/ids.js";
import { InventorySqlRepository } from "./sql-repository.js";
import type { StockPostingLine, StockStatus } from "./types.js";

const DECIMAL = /^-?\d+(?:\.\d+)?$/u;
function factor(scale: number): bigint { if (!Number.isInteger(scale) || scale < 0 || scale > 18) throw new PlatformError("VALIDATION_FAILED", "Invalid quantity scale", 400); return 10n ** BigInt(scale); }
function parseQuantity(quantity: QuantityV1): bigint {
  const raw = quantity.amount.trim();
  if (!DECIMAL.test(raw)) throw new PlatformError("VALIDATION_FAILED", "Quantity must be an exact decimal string", 400);
  const negative = raw.startsWith("-"); const unsigned = negative ? raw.slice(1) : raw; const [whole = "0", fraction = ""] = unsigned.split(".");
  if (fraction.length > quantity.scale) throw new PlatformError("VALIDATION_FAILED", "Quantity precision exceeds scale", 400);
  const value = BigInt(`${whole}${fraction.padEnd(quantity.scale, "0")}`.replace(/^0+(?=\d)/u, "") || "0"); return negative ? -value : value;
}
function formatQuantity(value: bigint, scale: number): string {
  if (scale === 0) return value.toString(); const negative = value < 0n; const absolute = negative ? -value : value; const raw = absolute.toString().padStart(scale + 1, "0");
  const fraction = raw.slice(-scale).replace(/0+$/u, ""); const output = fraction ? `${raw.slice(0, -scale)}.${fraction}` : raw.slice(0, -scale); return negative ? `-${output}` : output;
}

export class InventoryOperationsSqlRepository extends InventorySqlRepository {
  async createReservation(client: TransactionClient, context: RequestContext, input: {
    readonly id: string; readonly sourceType: string; readonly sourceId: string; readonly fulfillmentPolicy: "all_or_nothing" | "allow_partial"; readonly expiresAt?: string;
    readonly lines: readonly { readonly id: string; readonly variantId: string; readonly warehouseId: string; readonly quantity: QuantityV1 }[];
  }): Promise<Record<string, unknown>> {
    if (input.lines.length === 0) throw new PlatformError("VALIDATION_FAILED", "Reservation requires at least one line", 400);
    const replay = await client.query(`SELECT id::text,state,version::text,expires_at::text FROM inventory.stock_reservations WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, input.id]);
    if (replay.rows[0]) return replay.rows[0];
    if (input.expiresAt && new Date(input.expiresAt).getTime() <= Date.now()) throw new PlatformError("VALIDATION_FAILED", "Reservation expiry must be in the future", 400);
    const prepared: { line: typeof input.lines[number]; requested: bigint; reserved: bigint }[] = [];
    for (const line of input.lines) {
      const requested = parseQuantity(line.quantity); if (requested <= 0n) throw new PlatformError("VALIDATION_FAILED", "Reservation quantity must be positive", 400);
      const balances = await client.query<{ quantity_amount: string } & Record<string, unknown>>(`SELECT quantity_amount::text FROM inventory.stock_balances WHERE tenant_id=$1::uuid AND warehouse_id=$2::uuid AND variant_id=$3::uuid AND stock_status='sellable' AND unit_code=$4 AND quantity_scale=$5 FOR UPDATE`, [context.tenantId, line.warehouseId, line.variantId, line.quantity.unit, line.quantity.scale]);
      const onHand = balances.rows.reduce((sum, row) => sum + BigInt(row.quantity_amount), 0n);
      const active = await client.query<{ reserved: string } & Record<string, unknown>>(`SELECT COALESCE(SUM(l.reserved_quantity-l.consumed_quantity-l.released_quantity),0)::text AS reserved FROM inventory.stock_reservation_lines l JOIN inventory.stock_reservations h ON h.tenant_id=l.tenant_id AND h.id=l.reservation_id WHERE l.tenant_id=$1::uuid AND l.warehouse_id=$2::uuid AND l.variant_id=$3::uuid AND l.unit_code=$4 AND l.quantity_scale=$5 AND h.state IN ('fully_reserved','partially_reserved','partially_consumed')`, [context.tenantId, line.warehouseId, line.variantId, line.quantity.unit, line.quantity.scale]);
      const available = onHand - BigInt(active.rows[0]?.reserved ?? "0"); prepared.push({ line, requested, reserved: available <= 0n ? 0n : available < requested ? available : requested });
    }
    if (input.fulfillmentPolicy === "all_or_nothing" && prepared.some((item) => item.reserved !== item.requested)) for (const item of prepared) item.reserved = 0n;
    const reservedTotal = prepared.reduce((sum, item) => sum + item.reserved, 0n); const requestedTotal = prepared.reduce((sum, item) => sum + item.requested, 0n);
    const state = reservedTotal === 0n ? "unfulfilled" : reservedTotal === requestedTotal ? "fully_reserved" : "partially_reserved";
    await client.query(`INSERT INTO inventory.stock_reservations(id,tenant_id,source_type,source_id,state,fulfillment_policy,expires_at,created_by) VALUES($1::uuid,$2::uuid,$3,$4,$5,$6,$7::timestamptz,$8::uuid)`, [input.id, context.tenantId, input.sourceType, input.sourceId, state, input.fulfillmentPolicy, input.expiresAt ?? null, context.actorId]);
    for (const item of prepared) await client.query(`INSERT INTO inventory.stock_reservation_lines(id,tenant_id,reservation_id,variant_id,warehouse_id,unit_code,quantity_scale,requested_quantity,reserved_quantity) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6,$7,$8::numeric,$9::numeric)`, [item.line.id, context.tenantId, input.id, item.line.variantId, item.line.warehouseId, item.line.quantity.unit, item.line.quantity.scale, item.requested.toString(), item.reserved.toString()]);
    await this.evidence(client, context, `inventory.reservation.${state}.v1`, "stock_reservation", input.id, { state, sourceType: input.sourceType, sourceId: input.sourceId });
    return { id: input.id, state, version: "1", expiresAt: input.expiresAt ?? null };
  }

  async releaseReservation(client: TransactionClient, context: RequestContext, reservationId: string, expectedVersion: number): Promise<Record<string, unknown>> {
    const result = await client.query(`UPDATE inventory.stock_reservations SET state='released',updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid AND version=$3 AND state IN ('fully_reserved','partially_reserved','partially_consumed') RETURNING id::text,state,version::text`, [context.tenantId, reservationId, expectedVersion]);
    if (result.rowCount !== 1) throw new PlatformError("VERSION_CONFLICT", "Reservation state or version changed", 409);
    await client.query(`UPDATE inventory.stock_reservation_lines SET released_quantity=reserved_quantity-consumed_quantity,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND reservation_id=$2::uuid`, [context.tenantId, reservationId]);
    await this.evidence(client, context, "inventory.reservation.released.v1", "stock_reservation", reservationId, {}); return result.rows[0]!;
  }

  async consumeReservation(client: TransactionClient, context: RequestContext, input: { readonly reservationId: string; readonly expectedVersion: number; readonly quantities?: Readonly<Record<string, QuantityV1>> }): Promise<Record<string, unknown>> {
    const header = await client.query<{ state: string; version: string } & Record<string, unknown>>(`SELECT state,version::text FROM inventory.stock_reservations WHERE tenant_id=$1::uuid AND id=$2::uuid FOR UPDATE`, [context.tenantId, input.reservationId]);
    if (!header.rows[0]) throw new PlatformError("NOT_FOUND", "Reservation not found", 404); if (Number(header.rows[0].version) !== input.expectedVersion) throw new PlatformError("VERSION_CONFLICT", "Reservation version changed", 409);
    if (!["fully_reserved", "partially_reserved", "partially_consumed"].includes(header.rows[0].state)) throw new PlatformError("CONFLICT", "Reservation cannot be consumed", 409);
    const lines = await client.query<{ id: string; reserved_quantity: string; consumed_quantity: string; released_quantity: string } & Record<string, unknown>>(`SELECT id::text,reserved_quantity::text,consumed_quantity::text,released_quantity::text FROM inventory.stock_reservation_lines WHERE tenant_id=$1::uuid AND reservation_id=$2::uuid ORDER BY id FOR UPDATE`, [context.tenantId, input.reservationId]);
    let remainingTotal = 0n; let consumedTotal = 0n;
    for (const line of lines.rows) { const remaining = BigInt(line.reserved_quantity) - BigInt(line.consumed_quantity) - BigInt(line.released_quantity); const requested = input.quantities?.[line.id] === undefined ? remaining : parseQuantity(input.quantities[line.id]!); if (requested < 0n || requested > remaining) throw new PlatformError("VALIDATION_FAILED", "Consumption exceeds reservation", 400); await client.query(`UPDATE inventory.stock_reservation_lines SET consumed_quantity=consumed_quantity+$3::numeric,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, line.id, requested.toString()]); remainingTotal += remaining - requested; consumedTotal += BigInt(line.consumed_quantity) + requested; }
    const state = remainingTotal === 0n ? "consumed" : consumedTotal > 0n ? "partially_consumed" : header.rows[0].state; const result = await client.query(`UPDATE inventory.stock_reservations SET state=$3,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid RETURNING id::text,state,version::text`, [context.tenantId, input.reservationId, state]); await this.evidence(client, context, "inventory.reservation.consumed.v1", "stock_reservation", input.reservationId, { state }); return result.rows[0]!;
  }

  async createTransfer(client: TransactionClient, context: RequestContext, input: { readonly id: string; readonly legalEntityId: string; readonly sourceWarehouseId: string; readonly destinationWarehouseId: string; readonly lines: readonly { readonly id: string; readonly variantId: string; readonly quantity: QuantityV1; readonly batchId?: string; readonly serialIds?: readonly string[] }[] }): Promise<Record<string, unknown>> {
    if (input.sourceWarehouseId === input.destinationWarehouseId) throw new PlatformError("VALIDATION_FAILED", "Transfer warehouses must differ", 400); if (input.lines.length === 0) throw new PlatformError("VALIDATION_FAILED", "Transfer requires lines", 400);
    const replay = await client.query(`SELECT id::text,state,version::text FROM inventory.stock_transfers WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, input.id]); if (replay.rows[0]) return replay.rows[0];
    await client.query(`INSERT INTO inventory.stock_transfers(id,tenant_id,legal_entity_id,source_warehouse_id,destination_warehouse_id,requested_by) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5::uuid,$6::uuid)`, [input.id, context.tenantId, input.legalEntityId, input.sourceWarehouseId, input.destinationWarehouseId, context.actorId]);
    for (const line of input.lines) { const amount = parseQuantity(line.quantity); if (amount <= 0n) throw new PlatformError("VALIDATION_FAILED", "Transfer quantity must be positive", 400); await client.query(`INSERT INTO inventory.stock_transfer_lines(id,tenant_id,transfer_id,variant_id,unit_code,quantity_scale,requested_quantity,batch_id,serial_ids) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6,$7::numeric,$8::uuid,$9::uuid[])`, [line.id, context.tenantId, input.id, line.variantId, line.quantity.unit, line.quantity.scale, amount.toString(), line.batchId ?? null, line.serialIds ?? []]); }
    await this.evidence(client, context, "inventory.transfer.created.v1", "stock_transfer", input.id, { sourceWarehouseId: input.sourceWarehouseId, destinationWarehouseId: input.destinationWarehouseId }); return { id: input.id, state: "draft", version: "1" };
  }

  async approveTransfer(client: TransactionClient, context: RequestContext, input: { readonly transferId: string; readonly approvalId: string; readonly expectedVersion: number }): Promise<Record<string, unknown>> {
    const approval = await client.query(`SELECT id FROM platform.approval_requests WHERE tenant_id=$1::uuid AND id=$2::uuid AND status='approved' AND target_type='stock_transfer' AND target_id=$3`, [context.tenantId, input.approvalId, input.transferId]); if (approval.rowCount !== 1) throw new PlatformError("PERMISSION_DENIED", "Approved transfer approval is required", 403);
    const result = await client.query(`UPDATE inventory.stock_transfers SET state='approved',approved_by=$3::uuid,approval_id=$4::uuid,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid AND state='draft' AND version=$5 RETURNING id::text,state,version::text`, [context.tenantId, input.transferId, context.actorId, input.approvalId, input.expectedVersion]); if (result.rowCount !== 1) throw new PlatformError("VERSION_CONFLICT", "Transfer state or version changed", 409); await this.evidence(client, context, "inventory.transfer.approved.v1", "stock_transfer", input.transferId, { approvalId: input.approvalId }); return result.rows[0]!;
  }

  async dispatchTransfer(client: TransactionClient, context: RequestContext, input: { readonly transferId: string; readonly operationId: string; readonly postingGroupId: string }): Promise<Record<string, unknown>> {
    const header = await client.query<{ legal_entity_id: string; source_warehouse_id: string; destination_warehouse_id: string; state: string } & Record<string, unknown>>(`SELECT legal_entity_id::text,source_warehouse_id::text,destination_warehouse_id::text,state FROM inventory.stock_transfers WHERE tenant_id=$1::uuid AND id=$2::uuid FOR UPDATE`, [context.tenantId, input.transferId]);
    const transfer = header.rows[0]; if (!transfer) throw new PlatformError("NOT_FOUND", "Transfer not found", 404); if (transfer.state !== "approved") throw new PlatformError("CONFLICT", "Transfer must be approved", 409);
    const lines = await client.query<{ id: string; variant_id: string; unit_code: string; quantity_scale: number; requested_quantity: string; batch_id: string | null } & Record<string, unknown>>(`SELECT id::text,variant_id::text,unit_code,quantity_scale,requested_quantity::text,batch_id::text FROM inventory.stock_transfer_lines WHERE tenant_id=$1::uuid AND transfer_id=$2::uuid ORDER BY id FOR UPDATE`, [context.tenantId, input.transferId]);
    const postings: StockPostingLine[] = [];
    for (const line of lines.rows) { const amount = BigInt(line.requested_quantity); const common = { item: { itemId: line.variant_id, variantId: line.variant_id }, sourceDocumentId: input.transferId, sourceDocumentLineId: line.id, ...(line.batch_id ? { batchId: line.batch_id } : {}) }; postings.push({ ...common, warehouseId: transfer.source_warehouse_id, stockStatus: "sellable", quantityDelta: { amount: `-${formatQuantity(amount, line.quantity_scale)}`, unit: line.unit_code, scale: line.quantity_scale } }); postings.push({ ...common, warehouseId: transfer.destination_warehouse_id, stockStatus: "in_transit", quantityDelta: { amount: formatQuantity(amount, line.quantity_scale), unit: line.unit_code, scale: line.quantity_scale } }); }
    await this.postStock(client, context, { schemaVersion: "1.0", context: { tenantId: context.tenantId, legalEntityId: transfer.legal_entity_id, actorId: context.actorId, locale: context.locale, timeZone: context.timeZone, businessDate: context.businessDate }, operationId: input.operationId, postingGroupId: input.postingGroupId, movementType: "transfer_dispatch", sourceDocumentType: "stock_transfer", lines: postings, audit: { actorId: context.actorId, requestId: context.requestId, traceId: context.traceId } });
    await client.query(`UPDATE inventory.stock_transfer_lines SET dispatched_quantity=requested_quantity,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND transfer_id=$2::uuid`, [context.tenantId, input.transferId]); const result = await client.query(`UPDATE inventory.stock_transfers SET state='dispatched',dispatched_at=now(),updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid RETURNING id::text,state,version::text,dispatched_at::text`, [context.tenantId, input.transferId]); await this.evidence(client, context, "inventory.transfer.dispatched.v1", "stock_transfer", input.transferId, { postingGroupId: input.postingGroupId }); return result.rows[0]!;
  }

  async receiveTransfer(client: TransactionClient, context: RequestContext, input: { readonly transferId: string; readonly operationId: string; readonly postingGroupId: string; readonly lines: readonly { readonly lineId: string; readonly received: QuantityV1; readonly damaged?: QuantityV1; readonly missing?: QuantityV1 }[] }): Promise<Record<string, unknown>> {
    const header = await client.query<{ legal_entity_id: string; destination_warehouse_id: string; state: string } & Record<string, unknown>>(`SELECT legal_entity_id::text,destination_warehouse_id::text,state FROM inventory.stock_transfers WHERE tenant_id=$1::uuid AND id=$2::uuid FOR UPDATE`, [context.tenantId, input.transferId]); const transfer = header.rows[0]; if (!transfer) throw new PlatformError("NOT_FOUND", "Transfer not found", 404); if (!["dispatched", "partially_received"].includes(transfer.state)) throw new PlatformError("CONFLICT", "Transfer is not receivable", 409);
    const lines = await client.query<{ id: string; variant_id: string; unit_code: string; quantity_scale: number; dispatched_quantity: string; received_quantity: string; damaged_quantity: string; missing_quantity: string; batch_id: string | null } & Record<string, unknown>>(`SELECT id::text,variant_id::text,unit_code,quantity_scale,dispatched_quantity::text,received_quantity::text,damaged_quantity::text,missing_quantity::text,batch_id::text FROM inventory.stock_transfer_lines WHERE tenant_id=$1::uuid AND transfer_id=$2::uuid ORDER BY id FOR UPDATE`, [context.tenantId, input.transferId]); const byId = new Map(lines.rows.map((line) => [line.id, line])); const postings: StockPostingLine[] = [];
    for (const receipt of input.lines) { const line = byId.get(receipt.lineId); if (!line) throw new PlatformError("VALIDATION_FAILED", "Unknown transfer line", 400); const received = parseQuantity(receipt.received); const damaged = receipt.damaged ? parseQuantity(receipt.damaged) : 0n; const missing = receipt.missing ? parseQuantity(receipt.missing) : 0n; const remaining = BigInt(line.dispatched_quantity) - BigInt(line.received_quantity) - BigInt(line.damaged_quantity) - BigInt(line.missing_quantity); if (received < 0n || damaged < 0n || missing < 0n || received + damaged + missing > remaining) throw new PlatformError("VALIDATION_FAILED", "Transfer receipt exceeds remaining quantity", 400); const common = { item: { itemId: line.variant_id, variantId: line.variant_id }, warehouseId: transfer.destination_warehouse_id, sourceDocumentId: input.transferId, ...(line.batch_id ? { batchId: line.batch_id } : {}) }; const add = (amount: bigint, status: StockStatus, suffix: string): void => { if (amount === 0n) return; postings.push({ ...common, stockStatus: "in_transit", sourceDocumentLineId: `${line.id}:${suffix}`, quantityDelta: { amount: `-${formatQuantity(amount, line.quantity_scale)}`, unit: line.unit_code, scale: line.quantity_scale } }); if (status !== "in_transit") postings.push({ ...common, stockStatus: status, sourceDocumentLineId: `${line.id}:${suffix}`, quantityDelta: { amount: formatQuantity(amount, line.quantity_scale), unit: line.unit_code, scale: line.quantity_scale } }); }; add(received, "sellable", "received"); add(damaged, "damaged", "damaged"); add(missing, "in_transit", "missing"); await client.query(`UPDATE inventory.stock_transfer_lines SET received_quantity=received_quantity+$3::numeric,damaged_quantity=damaged_quantity+$4::numeric,missing_quantity=missing_quantity+$5::numeric,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, line.id, received.toString(), damaged.toString(), missing.toString()]); }
    if (postings.length === 0) throw new PlatformError("VALIDATION_FAILED", "Transfer receipt must account for stock", 400); await this.postStock(client, context, { schemaVersion: "1.0", context: { tenantId: context.tenantId, legalEntityId: transfer.legal_entity_id, actorId: context.actorId, locale: context.locale, timeZone: context.timeZone, businessDate: context.businessDate }, operationId: input.operationId, postingGroupId: input.postingGroupId, movementType: "transfer_receipt", sourceDocumentType: "stock_transfer", lines: postings, audit: { actorId: context.actorId, requestId: context.requestId, traceId: context.traceId } });
    const remaining = await client.query<{ count: string } & Record<string, unknown>>(`SELECT COUNT(*) FILTER(WHERE received_quantity+damaged_quantity+missing_quantity<dispatched_quantity)::text AS count FROM inventory.stock_transfer_lines WHERE tenant_id=$1::uuid AND transfer_id=$2::uuid`, [context.tenantId, input.transferId]); const state = BigInt(remaining.rows[0]?.count ?? "0") === 0n ? "received" : "partially_received"; const result = await client.query(`UPDATE inventory.stock_transfers SET state=$3,received_at=CASE WHEN $3='received' THEN now() ELSE received_at END,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid RETURNING id::text,state,version::text,received_at::text`, [context.tenantId, input.transferId, state]); await this.evidence(client, context, "inventory.transfer.received.v1", "stock_transfer", input.transferId, { state, postingGroupId: input.postingGroupId }); return result.rows[0]!;
  }

  async createCount(client: TransactionClient, context: RequestContext, input: { readonly id: string; readonly warehouseId: string; readonly blind: boolean; readonly items: readonly { readonly id: string; readonly variantId: string; readonly unit: string; readonly scale: number }[] }): Promise<Record<string, unknown>> {
    if (input.items.length === 0) throw new PlatformError("VALIDATION_FAILED", "Stock count requires items", 400); const replay = await client.query(`SELECT id::text,state,version::text,snapshot_at::text FROM inventory.stock_counts WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, input.id]); if (replay.rows[0]) return replay.rows[0]; await client.query(`INSERT INTO inventory.stock_counts(id,tenant_id,warehouse_id,state,blind,snapshot_at,created_by) VALUES($1::uuid,$2::uuid,$3::uuid,'frozen',$4,now(),$5::uuid)`, [input.id, context.tenantId, input.warehouseId, input.blind, context.actorId]);
    for (const item of input.items) { const balance = await client.query<{ amount: string } & Record<string, unknown>>(`SELECT COALESCE(SUM(quantity_amount),0)::text AS amount FROM inventory.stock_balances WHERE tenant_id=$1::uuid AND warehouse_id=$2::uuid AND variant_id=$3::uuid AND stock_status='sellable' AND unit_code=$4 AND quantity_scale=$5`, [context.tenantId, input.warehouseId, item.variantId, item.unit, item.scale]); await client.query(`INSERT INTO inventory.stock_count_lines(id,tenant_id,count_id,variant_id,unit_code,quantity_scale,expected_quantity) VALUES($1::uuid,$2::uuid,$3::uuid,$4::uuid,$5,$6,$7::numeric)`, [item.id, context.tenantId, input.id, item.variantId, item.unit, item.scale, balance.rows[0]?.amount ?? "0"]); }
    await this.evidence(client, context, "inventory.count.created.v1", "stock_count", input.id, { warehouseId: input.warehouseId }); return { id: input.id, state: "frozen", version: "1" };
  }

  async submitCount(client: TransactionClient, context: RequestContext, input: { readonly countId: string; readonly expectedVersion: number; readonly observations: Readonly<Record<string, QuantityV1>>; readonly recount: boolean }): Promise<Record<string, unknown>> {
    const header = await client.query<{ state: string; version: string } & Record<string, unknown>>(`SELECT state,version::text FROM inventory.stock_counts WHERE tenant_id=$1::uuid AND id=$2::uuid FOR UPDATE`, [context.tenantId, input.countId]); if (!header.rows[0]) throw new PlatformError("NOT_FOUND", "Stock count not found", 404); if (Number(header.rows[0].version) !== input.expectedVersion) throw new PlatformError("VERSION_CONFLICT", "Stock count version changed", 409); const allowed = input.recount ? ["recount_required"] : ["frozen", "counting"]; if (!allowed.includes(header.rows[0].state)) throw new PlatformError("CONFLICT", "Count is not accepting observations", 409);
    const lines = await client.query<{ id: string; unit_code: string; quantity_scale: number; expected_quantity: string } & Record<string, unknown>>(`SELECT id::text,unit_code,quantity_scale,expected_quantity::text FROM inventory.stock_count_lines WHERE tenant_id=$1::uuid AND count_id=$2::uuid ORDER BY id FOR UPDATE`, [context.tenantId, input.countId]); let variance = false;
    for (const line of lines.rows) { const observed = input.observations[line.id]; if (!observed) throw new PlatformError("VALIDATION_FAILED", `Missing observation ${line.id}`, 400); if (observed.unit !== line.unit_code || observed.scale !== line.quantity_scale) throw new PlatformError("VALIDATION_FAILED", "Observation dimensions mismatch", 400); const amount = parseQuantity(observed); if (amount < 0n) throw new PlatformError("VALIDATION_FAILED", "Count cannot be negative", 400); variance ||= amount !== BigInt(line.expected_quantity); const column = input.recount ? "recount_quantity" : "first_count_quantity"; const timestamp = input.recount ? "recounted_at" : "counted_at"; const actor = input.recount ? "recounter_id" : "counter_id"; await client.query(`UPDATE inventory.stock_count_lines SET ${column}=$3::numeric,${timestamp}=now(),${actor}=$4::uuid,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, line.id, amount.toString(), context.actorId]); }
    const state = !input.recount && variance ? "recount_required" : "submitted"; const result = await client.query(`UPDATE inventory.stock_counts SET state=$3,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid RETURNING id::text,state,version::text`, [context.tenantId, input.countId, state]); await this.evidence(client, context, "inventory.count.submitted.v1", "stock_count", input.countId, { state }); return result.rows[0]!;
  }

  async approveAndPostCount(client: TransactionClient, context: RequestContext, input: { readonly countId: string; readonly approvalId: string; readonly expectedVersion: number; readonly operationId: string; readonly postingGroupId: string }): Promise<Record<string, unknown>> {
    const approval = await client.query(`SELECT id FROM platform.approval_requests WHERE tenant_id=$1::uuid AND id=$2::uuid AND status='approved' AND target_type='stock_count' AND target_id=$3`, [context.tenantId, input.approvalId, input.countId]); if (approval.rowCount !== 1) throw new PlatformError("PERMISSION_DENIED", "Approved stock-count approval is required", 403);
    const header = await client.query<{ warehouse_id: string; state: string; version: string } & Record<string, unknown>>(`SELECT warehouse_id::text,state,version::text FROM inventory.stock_counts WHERE tenant_id=$1::uuid AND id=$2::uuid FOR UPDATE`, [context.tenantId, input.countId]); const count = header.rows[0]; if (!count) throw new PlatformError("NOT_FOUND", "Stock count not found", 404); if (count.state !== "submitted" || Number(count.version) !== input.expectedVersion) throw new PlatformError("VERSION_CONFLICT", "Stock count state or version changed", 409);
    const lines = await client.query<{ id: string; variant_id: string; unit_code: string; quantity_scale: number; expected_quantity: string; first_count_quantity: string | null; recount_quantity: string | null } & Record<string, unknown>>(`SELECT id::text,variant_id::text,unit_code,quantity_scale,expected_quantity::text,first_count_quantity::text,recount_quantity::text FROM inventory.stock_count_lines WHERE tenant_id=$1::uuid AND count_id=$2::uuid ORDER BY id FOR UPDATE`, [context.tenantId, input.countId]); const postings: StockPostingLine[] = [];
    for (const line of lines.rows) { const approved = BigInt(line.recount_quantity ?? line.first_count_quantity ?? line.expected_quantity); const variance = approved - BigInt(line.expected_quantity); await client.query(`UPDATE inventory.stock_count_lines SET approved_quantity=$3::numeric,variance_quantity=$4::numeric,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, line.id, approved.toString(), variance.toString()]); if (variance !== 0n) postings.push({ item: { itemId: line.variant_id, variantId: line.variant_id }, warehouseId: count.warehouse_id, stockStatus: "sellable", quantityDelta: { amount: formatQuantity(variance, line.quantity_scale), unit: line.unit_code, scale: line.quantity_scale }, sourceDocumentId: input.countId, sourceDocumentLineId: line.id }); }
    if (postings.length > 0) await this.postStock(client, context, { schemaVersion: "1.0", context: { tenantId: context.tenantId, ...(context.legalEntityId ? { legalEntityId: context.legalEntityId } : {}), actorId: context.actorId, locale: context.locale, timeZone: context.timeZone, businessDate: context.businessDate }, operationId: input.operationId, postingGroupId: input.postingGroupId, movementType: "physical_count_variance", sourceDocumentType: "stock_count", lines: postings, audit: { actorId: context.actorId, approverId: context.actorId, requestId: context.requestId, traceId: context.traceId, reason: "Approved count variance" }, approvalId: input.approvalId });
    const result = await client.query(`UPDATE inventory.stock_counts SET state='posted',approved_by=$3::uuid,approval_id=$4::uuid,posting_group_id=$5,posted_at=now(),updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid RETURNING id::text,state,version::text,posted_at::text`, [context.tenantId, input.countId, context.actorId, input.approvalId, input.postingGroupId]); await this.evidence(client, context, "inventory.count.posted.v1", "stock_count", input.countId, { postingGroupId: input.postingGroupId, varianceLines: postings.length }); return result.rows[0]!;
  }

  async expireReservations(client: TransactionClient, context: RequestContext): Promise<{ readonly expired: number }> {
    const candidates = await client.query<{ id: string } & Record<string, unknown>>(`SELECT id::text FROM inventory.stock_reservations WHERE tenant_id=$1::uuid AND expires_at<=now() AND state IN ('fully_reserved','partially_reserved','partially_consumed') ORDER BY expires_at FOR UPDATE SKIP LOCKED`, [context.tenantId]);
    for (const row of candidates.rows) { await client.query(`UPDATE inventory.stock_reservation_lines SET released_quantity=reserved_quantity-consumed_quantity,updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND reservation_id=$2::uuid`, [context.tenantId, row.id]); await client.query(`UPDATE inventory.stock_reservations SET state='expired',updated_at=now(),version=version+1 WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, row.id]); }
    if (candidates.rows.length > 0) await this.evidence(client, context, "inventory.reservations.expired.v1", "reservation_batch", uuidV7(), { count: candidates.rows.length }); return { expired: candidates.rows.length };
  }

  async runReconciliation(client: TransactionClient, context: RequestContext): Promise<Record<string, unknown>> {
    const runId = uuidV7(); await client.query(`INSERT INTO inventory.reconciliation_runs(id,tenant_id,state,requested_by) VALUES($1::uuid,$2::uuid,'running',$3::uuid)`, [runId, context.tenantId, context.actorId]); const dimensions = await this.reconciliationSummary(client, context); const mismatches = dimensions.filter((row) => row.matched !== true); const status = mismatches.length === 0 ? "matched" : "mismatch"; await client.query(`UPDATE inventory.reconciliation_runs SET state=$3,ledger_entry_count=(SELECT COUNT(*) FROM inventory.stock_ledger_entries WHERE tenant_id=$1::uuid),projection_key_count=$4,mismatch_count=$5,details=$6::jsonb,completed_at=now() WHERE tenant_id=$1::uuid AND id=$2::uuid`, [context.tenantId, runId, status, dimensions.length, mismatches.length, JSON.stringify(mismatches)]); await this.evidence(client, context, "inventory.reconciliation.completed.v1", "reconciliation_run", runId, { status, mismatchCount: mismatches.length }); return { id: runId, status, mismatchCount: mismatches.length };
  }

  async generateReplenishmentProposals(client: TransactionClient, context: RequestContext): Promise<readonly Record<string, unknown>[]> {
    const result = await client.query(`WITH balance AS (SELECT tenant_id,warehouse_id,variant_id,unit_code,quantity_scale,SUM(quantity_amount) FILTER(WHERE stock_status='sellable') AS on_hand FROM inventory.stock_balances WHERE tenant_id=$1::uuid GROUP BY tenant_id,warehouse_id,variant_id,unit_code,quantity_scale), reserved AS (SELECT l.tenant_id,l.warehouse_id,l.variant_id,l.unit_code,l.quantity_scale,SUM(l.reserved_quantity-l.consumed_quantity-l.released_quantity) AS amount FROM inventory.stock_reservation_lines l JOIN inventory.stock_reservations h ON h.tenant_id=l.tenant_id AND h.id=l.reservation_id WHERE l.tenant_id=$1::uuid AND h.state IN ('fully_reserved','partially_reserved','partially_consumed') GROUP BY l.tenant_id,l.warehouse_id,l.variant_id,l.unit_code,l.quantity_scale), incoming AS (SELECT pol.tenant_id,pol.warehouse_id,pol.variant_id,pol.unit_code,pol.quantity_scale,SUM(pol.ordered_quantity-pol.received_quantity-pol.cancelled_quantity) AS amount FROM procurement.purchase_order_lines pol JOIN procurement.purchase_orders po ON po.tenant_id=pol.tenant_id AND po.id=pol.purchase_order_id WHERE pol.tenant_id=$1::uuid AND po.state IN ('approved','partially_received') GROUP BY pol.tenant_id,pol.warehouse_id,pol.variant_id,pol.unit_code,pol.quantity_scale) SELECT policy.id::text,policy.variant_id::text,policy.warehouse_id::text,policy.supplier_id::text,policy.unit_code,policy.quantity_scale,(COALESCE(balance.on_hand,0)-COALESCE(reserved.amount,0))::text AS available,COALESCE(incoming.amount,0)::text AS incoming,GREATEST(policy.minimum_quantity,policy.maximum_quantity-(COALESCE(balance.on_hand,0)-COALESCE(reserved.amount,0))-COALESCE(incoming.amount,0))::text AS suggested_quantity,(current_date+policy.lead_time_days)::text AS required_by FROM inventory.reorder_policies policy LEFT JOIN balance USING(tenant_id,warehouse_id,variant_id,unit_code,quantity_scale) LEFT JOIN reserved USING(tenant_id,warehouse_id,variant_id,unit_code,quantity_scale) LEFT JOIN incoming USING(tenant_id,warehouse_id,variant_id,unit_code,quantity_scale) WHERE policy.tenant_id=$1::uuid AND policy.active AND (COALESCE(balance.on_hand,0)-COALESCE(reserved.amount,0)+COALESCE(incoming.amount,0))<=policy.reorder_point+policy.safety_stock ORDER BY required_by,policy.id`, [context.tenantId]); return result.rows;
  }

  async operationalHealth(client: TransactionClient, context: RequestContext): Promise<Record<string, unknown>> {
    const result = await client.query<{ ledger_cursor: string; projection_cursor: string; overdue_reservations: string; reconciliation_state: string | null; mismatch_count: string | null } & Record<string, unknown>>(
      `SELECT
         COALESCE((SELECT MAX(sequence_id) FROM inventory.stock_ledger_entries WHERE tenant_id=$1::uuid),0)::text AS ledger_cursor,
         COALESCE((SELECT MAX(source_cursor) FROM inventory.stock_balances WHERE tenant_id=$1::uuid),0)::text AS projection_cursor,
         COALESCE((SELECT COUNT(*) FROM inventory.stock_reservations WHERE tenant_id=$1::uuid AND expires_at<=now() AND state IN ('fully_reserved','partially_reserved','partially_consumed')),0)::text AS overdue_reservations,
         (SELECT state FROM inventory.reconciliation_runs WHERE tenant_id=$1::uuid ORDER BY started_at DESC LIMIT 1) AS reconciliation_state,
         (SELECT mismatch_count::text FROM inventory.reconciliation_runs WHERE tenant_id=$1::uuid ORDER BY started_at DESC LIMIT 1) AS mismatch_count`,
      [context.tenantId],
    );
    const row = result.rows[0]!; const lag = BigInt(row.ledger_cursor) - BigInt(row.projection_cursor); const mismatches = BigInt(row.mismatch_count ?? "0"); const overdue = BigInt(row.overdue_reservations);
    return { status: lag === 0n && mismatches === 0n ? "healthy" : "degraded", ledgerCursor: row.ledger_cursor, projectionCursor: row.projection_cursor, projectionLag: lag.toString(), overdueReservations: overdue.toString(), reconciliationState: row.reconciliation_state ?? "not_run", mismatchCount: mismatches.toString(), checkedAt: new Date().toISOString() };
  }

  private async evidence(client: TransactionClient, context: RequestContext, eventType: string, aggregateType: string, aggregateId: string, payload: Readonly<Record<string, unknown>>): Promise<void> {
    await client.query(`INSERT INTO platform.audit_events(id,tenant_id,event_type,action,outcome,actor_id,impersonator_id,target_type,target_id,request_id,trace_id,device_id,metadata,business_date,source_version) VALUES($1::uuid,$2::uuid,$3,$3,'success',$4::uuid,$5::uuid,$6,$7,$8,$9,$10::uuid,$11::jsonb,$12::date,'MOD-B-v1')`, [uuidV7(), context.tenantId, eventType, context.actorId, context.impersonatorId ?? null, aggregateType, aggregateId, context.requestId, context.traceId, context.deviceId ?? null, JSON.stringify(payload), context.businessDate]); await client.query(`INSERT INTO platform.outbox_events(id,tenant_id,event_type,aggregate_type,aggregate_id,schema_version,payload,metadata,correlation_id,causation_id,business_date) VALUES($1::uuid,$2::uuid,$3,$4,$5,'1.0',$6::jsonb,$7::jsonb,$8,$9,$10::date)`, [uuidV7(), context.tenantId, eventType, aggregateType, aggregateId, JSON.stringify(payload), JSON.stringify({ actorId: context.actorId, requestId: context.requestId, traceId: context.traceId }), context.traceId, context.requestId, context.businessDate]);
  }
}
