name = "store-management-api"
main = "src/index.ts"
compatibility_date = "2026-07-27"
compatibility_flags = ["nodejs_compat"]

[vars]
APP_ENV = "development"
REGION = "aws-us-east-2"
OIDC_ISSUER = "replace-in-deployment"
OIDC_AUDIENCE = "store-management-api"
OIDC_JWKS_URI = "replace-in-deployment"
OIDC_MFA_ACR_VALUES = "replace-in-deployment"

[[queues.producers]]
binding = "DOMAIN_EVENTS"
queue = "store-management-domain-events"

[[r2_buckets]]
binding = "OBJECTS"
bucket_name = "store-management-nonprod"

[[kv_namespaces]]
binding = "CONFIG_CACHE"
id = "replace-in-deployment"
